# Generated by Django 5.2.1 on 2025-05-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='utente',
        ),
    ]
