# Generated by Django 5.2.1 on 2025-05-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_evento_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descrizione',
            field=models.TextField(max_length=500),
        ),
    ]
