# Generated by Django 5.2.1 on 2025-05-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_evento_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descrizione',
            field=models.TextField(help_text='(max 100 caratteri)', max_length=100),
        ),
    ]
